# Use `ssh-keyscan -t ed25519 <hostname>...` to get the public key(s) remotely
[hosts.zheng]
ipAddress = "192.168.10.1"
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPok1B5NsawQoyxJ2Is3wynnfqZ51o1fyueJ3gpLLCa5"

[hosts.li]
ipAddress = "192.168.10.60"
syncthingId = "FWMZWNO-CIL5HZL-5IOA5IZ-UGXYQK6-DYK76L4-VDQAOZP-VHDLLC4-JYUSAAU"

[hosts.yang]
ipAddress = "192.168.10.10"
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBBqIBetzQSQhJeOgBXCcNwwyWToSGh2ZUMLEROwwxeF"

[hosts.wang]
ipAddress = "192.168.10.11"

[networks.home]
subnet = "192.168.10.0/16"
