name: "Build outputs"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    paths-ignore:
    - '*.md'
    - '*.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: '-source$'

    - run: nix run .#cachix-push
