name: Check the flake

on:
  workflow_dispatch:

  pull_request:
    paths-ignore:
    - 'README.*'
    - '.github/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - run: |
       nix flake check --update-input emacs-config \
           --no-write-lock-file --print-build-logs --show-trace
