name: Check the flake

on:
  workflow_dispatch:

  pull_request:

  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.ref }}

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - name: Check formatting
      run: nix develop -c treefmt --fail-on-change

    - run: nix flake check
