name: Check formatting

on:
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v21
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - name: Check formatting
      run: nix develop -c , check-format
