name: Cachix Deploy

on:
  workflow_dispatch:

  push:
    branches:
    - master
    paths:
    - 'machines/**'
    - 'profiles/**'
    - 'suites/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          flake-registry = https://raw.githubusercontent.com/akirak/flake-pins/master/registry.json

    - uses: cachix/cachix-action@v12
      with:
        name: akirak

    - name: Build the deploys
      id: build
      run: |
        spec=$(nix build .#cachix-deploys --print-out-paths)
        echo "spec_path=$spec" >> $GITHUB_OUTPUT

    - name: Push to Cachix
      run: |
        cachix push akirak $DEPLOY_SPEC
      env:
        DEPLOY_SPEC: ${{ steps.build.outputs.spec_path }}

    - name: Deploy
      run: |
        cachix deploy activate $DEPLOY_SPEC
      env:
        DEPLOY_SPEC: ${{ steps.build.outputs.spec_path }}
