name: Cachix Deploy

on:
  workflow_dispatch:

  push:
    branches:
    - master
    paths:
    - 'machines/**'
    - 'profiles/**'
    - 'suites/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          flake-registry = https://raw.githubusercontent.com/akirak/flake-pins/master/registry.json

    - uses: cachix/cachix-action@v12
      with:
        name: akirak

    - name: Build and deploy
      run: |
        spec=$(nix build .#cachix-deploys --print-out-paths)
        cachix push akirak $spec
        cachix deploy activate $spec
      env:
        CACHIX_ACTIVATE_TOKEN: ${{ secrets.CACHIX_ACTIVATE_TOKEN }}
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
